[package]
name = "rpg-dice-roller"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.16.0"
rand = "0.8.5"
winnow = "0.6.20"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "parsing"
harness = false
